version: "3.8"
name: "pals"

services:
  db:
    image: postgres
    container_name: pals-db
    restart: unless-stopped
    networks:
      - app_network
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  backend:
    build: .
    profiles: ["debug"]
    depends_on:
      db:
        condition: service_healthy
    networks: 
      - app_network
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    ports:
      - "${PORT}:${PORT}"

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
