version: 3

tasks:
  tidy:
    cmds:
      - go mod tidy

  run:
    cmds:
      - go run cmd/server/main.go

  dev:
    cmds:
      - wgo task run

  db:
    cmds:
      - go generate ./ent

  lint:
    cmds:
      - golangci-lint run

  format:
    cmds:
      - gofmt -w -s .

  other:
    cmds:
      - go run cmd/other/main.go
