version: 3

tasks:
  tidy:
    cmds:
      - go mod tidy

  run:
    cmds:
      - go run cmd/server/main.go

  dev:
    cmds:
      - wgo -file .go task run

  db:
    cmds:
      - go generate ./ent

  lint:
    cmds:
      - golangci-lint run

  format:
    cmds:
      - gofmt -w -s .

  test:
    cmds:
      #  TODO
      - go test -v ./...

  build:
    cmds:
      - go build -o bin/server cmd/server/main.go

  build:win:
    cmds:
      - GOOS=windows GOARCH=amd64 go build -o bin/server.exe cmd/server/main.go

  docker:build:
    cmds:
      - docker build -t pals-server .

  docker:run:
    cmds:
      - docker run -p 8000:8000 --env-file .env pals-server

  other:
    cmds:
      - go run cmd/other/main.go
