// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"irg1008/pals/ent/authrequest"
	"irg1008/pals/ent/schema"
	"irg1008/pals/ent/user"
	"irg1008/pals/ent/userdata"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	authrequestFields := schema.AuthRequest{}.Fields()
	_ = authrequestFields
	// authrequestDescToken is the schema descriptor for token field.
	authrequestDescToken := authrequestFields[2].Descriptor()
	// authrequest.DefaultToken holds the default value on creation for the token field.
	authrequest.DefaultToken = authrequestDescToken.Default.(func() uuid.UUID)
	// authrequestDescCreatedAt is the schema descriptor for created_at field.
	authrequestDescCreatedAt := authrequestFields[4].Descriptor()
	// authrequest.DefaultCreatedAt holds the default value on creation for the created_at field.
	authrequest.DefaultCreatedAt = authrequestDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescIsConfirmed is the schema descriptor for is_confirmed field.
	userDescIsConfirmed := userFields[2].Descriptor()
	// user.DefaultIsConfirmed holds the default value on creation for the is_confirmed field.
	user.DefaultIsConfirmed = userDescIsConfirmed.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	userdataFields := schema.UserData{}.Fields()
	_ = userdataFields
	// userdataDescCreatedAt is the schema descriptor for created_at field.
	userdataDescCreatedAt := userdataFields[5].Descriptor()
	// userdata.DefaultCreatedAt holds the default value on creation for the created_at field.
	userdata.DefaultCreatedAt = userdataDescCreatedAt.Default.(func() time.Time)
}
