// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuthRequest is the predicate function for authrequest builders.
type AuthRequest func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
